version = 1

exclude_patterns = ["public/mockServiceWorker.js"]

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "prettier"
enabled = true
