export { default as LoginInEmail } from './LoginInEmail.vue'
export { default as LoginInSocial } from './LoginInSocial.vue'
export { default as AccountDetail } from './AccountDetail.vue'
export { default as ManageAccount } from './ManageAccount.vue'
export { default as OnlyButton } from './OnlyButton.vue'
