on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: '@storipress/builder-component'
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '16'
          cache: 'yarn'
      - name: publish package
        if: ${{ steps.release.outputs.release_created }}
        run: |
          yarn
          yarn npm publish
