name: Unit Test

on: [push]

jobs:
  unit-test:
    runs-on: [self-hosted]
    name: Test
    env:
      NODE_OPTIONS: --max-old-space-size=6144
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn
      - run: yarn test --coverage
